# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
name: pkgdown.yaml

on:
  push:
    branches: [main, develop]
  pull_request:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  pkgdown:
    runs-on: ubuntu-22.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::.
          needs: website
          cache: true
          cache-version: 1

      - name: Build site
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE, devel = FALSE)
        shell: Rscript {0}

      - name: Upload artifact 📦
        if: github.event_name != 'pull_request'
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs'

      - name: Deploy to GitHub Pages 🚀
        if: github.event_name != 'pull_request'
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Print site URL 🔗
        if: github.event_name != 'pull_request'
        run: |
          echo "🔗 **[https://ohdsi.github.io/ARTEMIS/](https://ohdsi.github.io/ARTEMIS/)**" >> $GITHUB_STEP_SUMMARY
